export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surfboards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'An enchanted forest with floating lanterns, digital painting',
  'A retro arcade room with glowing neon lights and arcade machines, digital art',
  'A magical underwater city inhabited by mermaids, digital painting',
  'A steampunk airship soaring through the clouds, digital art',
  'A majestic dragon resting on a mountaintop, digital painting',
  'A futuristic cityscape at night with flying cars and holographic billboards, digital art',
  'A mystical forest with glowing mushrooms and fairies, digital painting',
  'A time traveler standing in front of a wormhole, digital art',
  'An alien planet with floating islands and colorful flora, digital painting',
  'A haunted mansion with bats flying around, illuminated by a full moon, digital art',
  'A futuristic cyberpunk street scene with hoverboards and neon signs, digital painting',
  'A fantasy castle surrounded by a moat and lush gardens, digital art',
  'A magical book with glowing pages and flying letters, digital painting',
  'A celestial scene with planets, stars, and galaxies, digital art',
  'A whimsical carousel with intricately designed animals, digital painting',
  'A post-apocalyptic wasteland with ruins and overgrown vegetation, digital art',
  'A mystical waterfall hidden in a secret forest, digital painting',
  'A spaceship exploring the depths of space, surrounded by nebulae and stars, digital art',
  'A futuristic city skyline at sunset, with holographic skyscrapers, digital painting',
  'A whimsical tea party with talking animals and floating teacups, digital art',
  'A magical ice palace with ice sculptures and shimmering crystals, digital painting',
  'A cosmic journey through a wormhole, with vibrant colors and light effects, digital art',
  'An underwater coral reef teeming with colorful fish and marine life, digital painting',
  'A hidden treasure chest buried on a deserted island, surrounded by palm trees, digital art',
  'A steampunk-inspired train traveling through a mountainous landscape, digital painting',
  'A mythical creature with wings and a majestic aura, surrounded by nature, digital art',
  'A futuristic laboratory with advanced technology and glowing vials, digital painting',
  'A dreamy floating island with waterfalls and lush vegetation, digital art',
  'A surreal landscape with floating islands and upside-down trees, digital painting',
  'A city skyline transformed into a futuristic utopia, with sleek architecture and flying vehicles, digital art',
  'A whimsical underwater scene with mermaids, dolphins, and colorful coral, digital painting',
  'A secret garden filled with enchanted flowers and magical creatures, digital art',
  'A cosmic explosion of colors and shapes, representing the birth of a new universe, digital painting',
  'A time-lapse of a flower blooming, capturing its vibrant colors and delicate petals, digital art',
  'A journey through a mystical portal into a world of imagination and wonder, digital painting',
  'A futuristic space station orbiting a distant planet, with astronauts floating in zero gravity, digital art',
  'An ancient temple hidden in the depths of a lush jungle, with mysterious symbols and artifacts, digital painting',
  'A fantastical steampunk airship race through the clouds, with competitors from different worlds, digital art',
  'A majestic waterfall cascading down a mountain, surrounded by pristine nature, digital painting',
  'A surreal underwater scene with bioluminescent creatures and glowing plants, digital art',
  'A futuristic robot factory with assembly lines and advanced robotic arms, digital painting',
  'A floating city above the clouds, with gravity-defying architecture and breathtaking views, digital art',
  'A mystical firebird soaring through the sky, leaving a trail of vibrant colors, digital painting',
  'A futuristic space colony on a distant planet, with domed habitats and advanced technology, digital art',
  'A peaceful zen garden with raked sand, carefully placed rocks, and a tranquil pond, digital painting',
  'A magical portal opening in the middle of a dense forest, revealing a hidden realm, digital art',
  'A mythical creature emerging from the depths of a dark forest, with glowing eyes and majestic horns, digital painting',
  'A futuristic hovercraft speeding across a desert landscape, leaving a trail of dust and sand, digital art',
  'A serene mountain landscape with snow-capped peaks and a calm lake, reflecting the beauty of nature, digital painting',
  'A surreal dreamscape with floating islands and surreal creatures, blending reality and imagination, digital art',
  'A futuristic city engulfed in a glowing energy shield, protecting it from external threats, digital painting',
  'A mystical moonlit forest with sparkling fireflies and ancient trees, whispering secrets of the past, digital art',
  'A magical library filled with floating books and ancient knowledge, waiting to be discovered, digital painting',
  'A cosmic dance of celestial bodies, portraying the beauty and vastness of the universe, digital art',
  'An otherworldly landscape with towering rock formations and glowing geodes, hiding ancient mysteries, digital painting',
  'A futuristic race track with anti-gravity vehicles, racing at incredible speeds, surrounded by a cheering crowd, digital art',
  'A tranquil beach at sunset, with gentle waves and a colorful sky, inviting peace and relaxation, digital painting',
  'A mythical underwater city with elegant architecture and enchanting mermaids, digital art',
  'A steampunk-inspired cityscape with towering buildings, steam-powered machines, and airships, digital painting',
  'A futuristic battle scene with mechs and energy weapons, showcasing the intensity of futuristic warfare, digital art',
  'A whimsical village in the clouds, with houses floating on cotton candy clouds and candy cane lampposts, digital painting',
  'A surreal desert landscape with giant cacti and a glowing sunset, capturing the essence of a dream, digital art',
  'A futuristic cyberpunk marketplace with neon signs, holographic advertisements, and bustling crowds, digital painting',
  'A magical night sky filled with shooting stars and a mesmerizing display of colors, igniting the imagination, digital art',
  'An ancient ruin in the heart of a dense jungle, with intricate carvings and hidden treasures, digital painting',
  'A futuristic sports arena with holographic displays and high-tech equipment, where champions are born, digital art',
  'A serene winter scene with a snow-covered forest and a cozy cabin, emanating warmth and tranquility, digital painting',
  'A fantastical steampunk cityscape with towering clock towers, brass contraptions, and steam-powered transportation, digital art',
  'A mythical creature guarding a hidden treasure, deep within the heart of a treacherous maze, digital painting',
  'A futuristic space battle with laser cannons and swirling energy fields, depicting the clash of advanced civilizations, digital art',
  'A whimsical garden with oversized flowers, talking animals, and a magical atmosphere, digital painting',
  'A surreal underwater world with vibrant coral reefs, exotic fish, and hidden mermaid kingdoms, digital art',
  'A futuristic laboratory with glowing test tubes, scientific equipment, and groundbreaking discoveries, digital painting',
  'A mystical forest with towering trees, glowing mushrooms, and ethereal light filtering through the canopy, digital art',
  'A cosmic journey through a wormhole, with swirling colors and distorted reality, digital painting',
  'An underwater cave filled with bioluminescent creatures, creating a mesmerizing display of light, digital art',
  'A steampunk-inspired flying machine soaring through the skies, propelled by gears and steam, digital painting',
  'A futuristic cityscape at dusk, with neon lights and flying vehicles, evoking a sense of awe and wonder, digital art',
  'A magical underwater garden with floating plants and playful sea creatures, digital painting',
  'A mysterious portal to a different dimension, shimmering with unknown energies, digital art',
  'A futuristic spaceship interior, with sleek designs and advanced technology, digital painting',
  'A mythical creature galloping through a mystical forest, leaving trails of magic in its wake, digital art',
  'A surreal dreamscape with floating islands and surreal creatures, blending reality and imagination, digital painting',
  'A futuristic city engulfed in a glowing energy shield, protecting it from external threats, digital art',
  'A mystical moonlit forest with sparkling fireflies and ancient trees, whispering secrets of the past, digital painting',
  'A magical library filled with floating books and ancient knowledge, waiting to be discovered, digital art',
  'A cosmic dance of celestial bodies, portraying the beauty and vastness of the universe, digital painting',
  'An otherworldly landscape with towering rock formations and glowing geodes, hiding ancient mysteries, digital art',
  'A futuristic race track with anti-gravity vehicles, racing at incredible speeds, surrounded by a cheering crowd, digital painting',
  'A tranquil beach at sunset, with gentle waves and a colorful sky, inviting peace and relaxation, digital art',
  'A mythical underwater city with elegant architecture and enchanting mermaids, digital painting',
  'A steampunk-inspired cityscape with towering buildings, steam-powered machines, and airships, digital art',
  'A futuristic battle scene with mechs and energy weapons, showcasing the intensity of futuristic warfare, digital painting',
  'A whimsical village in the clouds, with houses floating on cotton candy clouds and candy cane lampposts, digital art',
  'A surreal desert landscape with giant cacti and a glowing sunset, capturing the essence of a dream, digital painting',
  'A futuristic cyberpunk marketplace with neon signs, holographic advertisements, and bustling crowds, digital painting',
  'A magical night sky filled with shooting stars and a mesmerizing display of colors, igniting the imagination, digital art',
  'An ancient ruin in the heart of a dense jungle, with intricate carvings and hidden treasures, digital painting',
  'A futuristic sports arena with holographic displays and high-tech equipment, where champions are born, digital art',
  'A serene winter scene with a snow-covered forest and a cozy cabin, emanating warmth and tranquility, digital painting',
  'A fantastical steampunk cityscape with towering clock towers, brass contraptions, and steam-powered transportation, digital art',
  'A mythical creature guarding a hidden treasure, deep within the heart of a treacherous maze, digital painting',
  'A futuristic space battle with laser cannons and swirling energy fields, depicting the clash of advanced civilizations, digital art',
  'A whimsical garden with oversized flowers, talking animals, and a magical atmosphere, digital painting',
  'A surreal underwater world with vibrant coral reefs, exotic fish, and hidden mermaid kingdoms, digital art',
  'A futuristic laboratory with glowing test tubes, scientific equipment, and groundbreaking discoveries, digital painting',
  'A mystical forest with towering trees, glowing mushrooms, and ethereal light filtering through the canopy, digital art',
  'A cosmic journey through a wormhole, with swirling colors and distorted reality, digital painting',
  'An underwater cave filled with bioluminescent creatures, creating a mesmerizing display of light, digital art',
  'A steampunk-inspired flying machine soaring through the skies, propelled by gears and steam, digital painting',
  'A futuristic cityscape at dusk, with neon lights and flying vehicles, evoking a sense of awe and wonder, digital art',
  'A magical underwater garden with floating plants and playful sea creatures, digital painting',
  'A mysterious portal to a different dimension, shimmering with unknown energies, digital art',
  'A futuristic spaceship interior, with sleek designs and advanced technology, digital painting',
  'A mythical creature galloping through a mystical forest, leaving trails of magic in its wake, digital art',
  'A surreal dreamscape with floating islands and surreal creatures, blending reality and imagination, digital painting',
  'A futuristic city engulfed in a glowing energy shield, protecting it from external threats, digital art',
  'A mystical moonlit forest with sparkling fireflies and ancient trees, whispering secrets of the past, digital painting',
  'A magical library filled with floating books and ancient knowledge, waiting to be discovered, digital art',
  'A cosmic dance of celestial bodies, portraying the beauty and vastness of the universe, digital painting',
  'An otherworldly landscape with towering rock formations and glowing geodes, hiding ancient mysteries, digital art',
  'A futuristic race track with anti-gravity vehicles, racing at incredible speeds, surrounded by a cheering crowd, digital painting',
  'A tranquil beach at sunset, with gentle waves and a colorful sky, inviting peace and relaxation, digital art',
  'A mythical underwater city with elegant architecture and enchanting mermaids, digital painting',
  'A steampunk-inspired cityscape with towering buildings, steam-powered machines, and airships, digital art',
  'A futuristic battle scene with mechs and energy weapons, showcasing the intensity of futuristic warfare, digital painting',
  'A whimsical village in the clouds, with houses floating on cotton candy clouds and candy cane lampposts, digital art',
  'A surreal desert landscape with giant cacti and a glowing sunset, capturing the essence of a dream, digital painting',
  'A futuristic cyberpunk marketplace with neon signs, holographic advertisements, and bustling crowds, digital painting',
  'A magical night sky filled with shooting stars and a mesmerizing display of colors, igniting the imagination, digital art',
  'An ancient ruin in the heart of a dense jungle, with intricate carvings and hidden treasures, digital painting',
  'A futuristic sports arena with holographic displays and high-tech equipment, where champions are born, digital art',
  'A serene winter scene with a snow-covered forest and a cozy cabin, emanating warmth and tranquility, digital painting',
  'A fantastical steampunk cityscape with towering clock towers, brass contraptions, and steam-powered transportation, digital art',
  'A mythical creature guarding a hidden treasure, deep within the heart of a treacherous maze, digital painting',
  'A futuristic space battle with laser cannons and swirling energy fields, depicting the clash of advanced civilizations, digital art',
  'A whimsical garden with oversized flowers, talking animals, and a magical atmosphere, digital painting',
  'A surreal underwater world with vibrant coral reefs, exotic fish, and hidden mermaid kingdoms, digital art',
];